# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mini-smtp-server}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gough"]
  s.date = %q{2010-11-05}
  s.description = %q{A small and simple SMTP server}
  s.email = %q{aaron@aarongough.com}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mini-smtp-server.rb",
     "lib/mini-smtp-server/mini-smtp-server.rb",
     "mini-smtp-server.gemspec",
     "test/setup/.gitignore",
     "test/setup/custom_assertions.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/mini_smtp_server_test.rb"
  ]
  s.homepage = %q{https://github.com/aarongough/mini-smtp-server}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A small and simple SMTP server}
  s.test_files = [
    "test/setup/custom_assertions.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/mini_smtp_server_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

